[main]
font=monospace:size=14
dpi-aware=no
pad=35x35
initial-window-size-chars=90x28

[scrollback]
lines=0

[cursor]
blink=no

[mouse]
hide-when-typing=yes

[bell]
system=no

[colors-dark]
#alpha=0.7
#background=141c21
background=000000
foreground=93a1a1
regular0=263640  # black
regular1=d12f2c  # red
regular2=819400  # green
regular3=b08500  # yellow
regular4=2587cc  # blue
regular5=696ebf  # magenta
regular6=289c93  # cyan
regular7=bfbaac  # white
bright0=4a697d   # bright black
bright1=fa3935   # bright red
bright2=a4bd00   # bright green
bright3=d9a400   # bright yellow
bright4=2ca2f5   # bright blue
bright5=8086e8   # bright magenta
bright6=33c5ba   # bright cyan
bright7=fdf6e3   # bright white

